#
###################################
# Site wide configuration
####################################
#
title: fbirk blog
email:
description: A simple and awesome blog theme powered by jekyll.
url: https://fbirk.github.io/homepage/
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Germany
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: fbirk
  avatar: leonids-logo.png
  job: "cs student"
  bio: "My own small space in the web."
  email:
  github: fbirk
